version: '3.8'
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=planets
      - MONGO_DB_USERNAME=admin
      - MONGO_DB_PASSWORD=admin
    volumes:
      - C:\mongodb\data:/data/db/
      - C:\mongodb\log:/var/log/mongodb/
      - C:\mongodb\initdb.d:/docker-entrypoint-initdb.d
    networks:
      - main-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: planets-api
    container_name: planets-api
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=admin
      - SPRING_DATA_MONGODB_PASSWORD=admin
      - SPRING_DATA_MONGODB_DATABASE=planets
    networks:
      - main-network

networks:
  main-network:
    name: planets-network
